name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        name: Use Node.js
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: pnpm run build
        env:
          VERSION: v0.0.0