name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v6
        name: Use Node.js
        with:
          node-version: 22.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: pnpm run build
        env:
          VERSION: v0.0.0
